### ISSUE TITLE
cities.xlsx not found 

### ISSUE THREAD

**Issue by daltonthethird** [learn-co-curriculum/dsc-dictionaries-lab#4]
./cities.xlsx not found when trying to import to lesson. 
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-51-cd755be98823>](https://localhost:8080/#) in <cell line: 3>()
      1 import pandas as pd
      2 file_name = './cities.xlsx'
----> 3 travel_df = pd.read_excel(file_name)
      4 cities = travel_df.to_dict('records')

3 frames
[/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py](https://localhost:8080/#) in read_excel(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend)
    476     if not isinstance(io, ExcelFile):
    477         should_close = True
--> 478         io = ExcelFile(io, storage_options=storage_options, engine=engine)
    479     elif engine and engine != io.engine:
    480         raise ValueError(

[/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py](https://localhost:8080/#) in __init__(self, path_or_buffer, engine, storage_options)
   1494                 ext = "xls"
   1495             else:
-> 1496                 ext = inspect_excel_format(
   1497                     content_or_path=path_or_buffer, storage_options=storage_options
   1498                 )

[/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py](https://localhost:8080/#) in inspect_excel_format(content_or_path, storage_options)
   1369         content_or_path = BytesIO(content_or_path)
   1370 
-> 1371     with get_handle(
   1372         content_or_path, "rb", storage_options=storage_options, is_text=False
   1373     ) as handle:

[/usr/local/lib/python3.10/dist-packages/pandas/io/common.py](https://localhost:8080/#) in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    866         else:
    867             # Binary mode
--> 868             handle = open(handle, ioargs.mode)
    869         handles.append(handle)
    870 

FileNotFoundError: [Errno 2] No such file or directory: './cities.xlsx'

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for raising this issue. There appears to have been an update with Numpy.

Go to your terminal and for your learn-env (or whatever environment you are using, but I assume it is that one):

`conda install -c anaconda openpyxl`

Install and if it asks you any questions, then responding 'Y' should be the correct choice.

After openpyxl has been correctly installed, try again with a "fresh" kernel and you should be good to go.
